### ISSUE TITLE
rooms.c data source

### ISSUE THREAD

**Issue by NoneGiven** [hackyourlife/mph-viewer#1]
I'm finally back to poking around with MPH formats. I wrote a model viewer of my own that's basically just an improved dsgraph, with some export features (including COLLADA export copied from [mph-model-viewer](https://github.com/McKay42/mph-model-viewer)) and a lot of format info copied from your repo.

I'll probably have several questions at some point in time, especially about animations, if you don't mind. But for right now a simpler question: Was the information in rooms.c (fog and light settings, for example) extracted from the game somewhere, and if so where?

**Comment by hackyourlife** [comment]
> Was the information in rooms.c (fog and light settings, for example) extracted from the game somewhere, and if so where?

It's from the game's ARM9 program binary, and it's not stored anywhere else unfortunately. That's why I included it in a c file in this repository, because you cannot easily obtain that information otherwise.

**Comment by NoneGiven** [comment]
I assume the code also contain the relationships between files for external textures and stuff like that? And also the full map layouts (what room to load next at each door). Not that's it's too hard to stitch that information together yourself.

How much interest do you have in model loading beyond each room's specific entities? I can do some PRs for basic stuff like single model loading, with handling of external files and using specific recolors. Still trying to figure out more about other formats like collision, but I'm very slow.

**Comment by hackyourlife** [comment]
> I assume the code also contain the relationships between files for external textures and stuff like that?

Yes, the game code has functions to load certain entity types, and some entity types like "objects" and so on have shared textures, which are hardcoded in those functions. I'm using this information when loading entities.

> And also the full map layouts (what room to load next at each door).

I didn't see anything like that so far. From what I've seen so far, it's quite likely that the game uses the collision files and door + portal nodes to decide where to go and what to load next. It also seems like there is always space for two rooms in RAM at a time, and one of the two rooms is a "connector" room. Looking at the code purely with static analysis tools (which is what I did so far) is hard, so I decided to eventually make tools to look into the game's internals while it's running to quickly get all the otherwise hard to get information (like data structures, loaded overlay files, …), but that's not yet finished.

> How much interest do you have in model loading beyond each room's specific entities?

You mean like directly viewing individual models? If you want to add that and if it doesn't make the code of the existing "main" program unnecessarily complex: sure. If it turns out to make the code of the existing "main" program too complex, you could also add a new "main" program for this, like e.g. a new "view-model" tool next to the existing "dsgraph".

My plan was/is to eventually load a complete room with all entities + models + animations + particle systems (called "effects" in this game) + scan logs + collision data + camera paths + …, maybe even enemies, hunters and so on, and render everything as accurate as possible, but I didn't work on it for a while.

> Still trying to figure out more about other formats like collision, but I'm very slow.

Figuring out formats like collision data, particle systems, camera paths, animations, … isn't really easy at all, unless you start to look at the game with a debugger or static analysis tool.

**Comment by NoneGiven** [comment]
Yeah, I just mean being able to load in arbitrary models. It could load them into the scene along with everything else or it could be standalone. The important thing functionality-wise is being able to tell it "load Trace_lod1" and have it pick up the external texture files and choose a recolor, etc.

>My plan was/is to eventually load a complete room with all entities + models + animations + particle systems (called "effects" in this game) + scan logs + collision data + camera paths + …, maybe even enemies, hunters and so on, and render everything as accurate as possible, but I didn't work on it for a while.

That would be incredible. What you have already is very impressive, though! Hopefully you can keep working on it. I totally get the time it takes to work on a huge hobby project like this when you have other stuff going on. My very, very long-term goal is to basically import all the MPH assets into Unity and reprogram the game. I could do a lot right now, but I want the animations and collisions accurately reproduced and not just approximated.

Let me know if there's anything I can do to help this project. I'm technical enough to understand all the concepts involved, although I don't have a lot of experience in reverse engineering beyond figuring basic stuff out through memory watching. I'm much more versed in the gameplay side of things, but I'm learning.
