### ISSUE TITLE
Entity info

### ISSUE THREAD

**Issue by NoneGiven** [hackyourlife/mph-viewer#5]
I started going through the entity types to figure out a few fields. Haven't got too deep into it, and before I do I wondered, can you share the format info you mentioned for other entity types? If you've already got just the format I can put together a list of the model IDs for platforms, objects, etc.

Here's what little I have so far -- you may already have all this.

- All the structs start with the 4-byte header and the 12-byte position vector
- Type 2 is a player spawn point (single-player and multiplayer)
- Type 6 is a spawner for enemies, keys, etc.
- Type 11 is a camera position, e.g. for side views of Morph Ball puzzles, maybe also spectator cam

And a few properties for the type 3 - door format (total size 104):

| Offset | Type | Description
| - | - | - |
| 0x00 | Header (4) | |
| 0x04 | Vector3Fx (12) | Position |
| 0x1C | Vector3Fx (12) | Facing direction (unit vector) |
| 0x38 | uint (4) | Some ID |
| 0x3C | uint (4) | Model ID |
| 0x48 | string (32) | Name |

| Model ID | Model |
| - | - |
| 0 | AlimbicDoor |
| 1 | AlimbicMorphBallDoor |
| 2 | AlimbicBossDoor |
| 3 | AlimbicThinDoor |

I made a toggle in my viewer (not in master yet) to render unknown entities with the unused pick_wpn_missile model in different colors -- looks pretty nice.

![01](https://user-images.githubusercontent.com/2163967/83666424-eee8c400-a59a-11ea-809e-386d6b2b7191.jpg)

![02](https://user-images.githubusercontent.com/2163967/83666437-f4460e80-a59a-11ea-804e-6db521325ca7.jpg)

**Comment by hackyourlife** [comment]
I have a lot of this information in some database, but since I'm working on one piece at a time, it's not in this repository right now.

The entity types I know that exist:
```
PLATFORM         EQU 0
OBJECT           EQU 1
ALIMBIC_DOOR     EQU 3
ITEM             EQU 4
ITEM_INSTANCE    EQU 5
ENEMY            EQU 6
JUMP_PAD         EQU 9
TELEPORTER       EQU 0xE
ARTIFACT         EQU 0x11
CAMERA_SEQ       EQU 0x12
FORCE_FIELD      EQU 0x13
ENEMY_INSTANCE   EQU 0x17
ENERGY_BEAM      EQU 0x1A
ENTITY_LIST_HEAD EQU 0x1B
```

Entities are generally weird. There is an `ITEM` entity, which is stored in the entity file, but then the game parses those entities and dynamically generates `ITEM_INSTANCE` entities at runtime, which are displayed in the game. The same for enemies. This makes analyzing entity data a bit … harder.

The structure of the door entity (excluding the header):
```
EntityDoor      struc
pos             VecFx32 ?
vec1            VecFx32 ?
vec2            VecFx32 ?
node_name       DCB 16 dup(?)
palette_id      DCD ?
type            DCD ?
field_3C        DCD ?
target_layer_id DCW ?
field_42        DCB ?
field_43        DCB ?
ent_filename    DCB 16 dup(?)
room_name       DCB 16 dup(?)
field_64        DCD ?
EntityDoor      ends
```

The model filenames and animation filenames for the doors:
```c
char* alimbic_door_model_names[4] = {
  "models/AlimbicDoor_Model.bin",
  "models/AlimbicMorphBallDoor_mdl_Model.bin",
  "models/AlimbicBossDoor_Model.bin",
  "models/AlimbicThinDoor_Model.bin"
};

char* alimbic_door_animation_names[4] = {
  "models/AlimbicDoor_Anim.bin",
  "models/AlimbicMorphBallDoor_mdl_Anim.bin",
  "models/AlimbicBossDoor_Anim.bin",
  "models/AlimbicThinDoor_Anim.bin"
};
```

In general, for every ID based thing in the game (e.g. door types, item types, enemy types, object types, …) there is an array of filenames in the game code somewhere. One thing you probably didn't see so far is "fx" which seems to be particle systems.

I don't know which information you need right now, and I don't feel like going through all of this and post it in some unstructured Github issues at the moment, but I already documented many structures to some extent. Once I implement the corresponding entity types in the viewer, the relevant parts will appear in this repo. And I think discussing this in Github issues is unnecessarily slow. You could join the "MetroiDS Hacking" Discord (https://discord.gg/QpAm9h), that's where I usually post stuff I'm working on, and that's where you would get much faster responses. Right now I'm working on a better analysis tool btw, so hopefully there will be much more stuff coming soon.

Finally, I just pushed a few changes, including a hacky implementation of fog, properly transformed jump pads, animated jump pad bases, fixes for some transparency related glitches (e.g. for the E tank glitch), and a few more bug fixes. The whole project should now compile on Linux too.
